name: Deploy to ECS

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker build -t devops-static .
          docker tag devops-static:latest 717211314188.dkr.ecr.us-east-2.amazonaws.com/devops-static:latest
          docker push 717211314188.dkr.ecr.us-east-2.amazonaws.com/devops-static:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster devops-static --service devops-static-website --force-new-deployment --region us-east-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
